title: Portfolio
author: Vandana Singh
email: fidatovandana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I love to see myself progressing  in the field I love.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
